#!/system/bin/sh
ZIPALIGNDB=/data/zipalign.db;
if [ ! -f $ZIPALIGNDB ]; then
	touch $ZIPALIGNDB;
fi;
for DIR in /system/app /data/app /system/priv-app; do
cd $DIR;
for APK in *.apk; do
if [ $APK -ot $ZIPALIGNDB ] && [ $(grep "$DIR/$APK" $ZIPALIGNDB|wc -l) -gt 0 ]
else 
ZIPCHECK=`/system/xbin/zipalign -c -v 4 $APK | grep FAILED | wc -l`;
if [ $ZIPCHECK == "1" ]; then
/system/xbin/zipalign -v -f 4 $APK /data/local/$APK;
busybox mount -o rw,remount /system;
cp -f -p /data/local/$APK $APK;
grep "$DIR/$APK" $ZIPALIGNDB > /dev/null || echo $DIR/$APK >> $ZIPALIGNDB;
else
grep "$DIR/$APK" $ZIPALIGNDB > /dev/null || echo $DIR/$APK >> $ZIPALIGNDB;
fi;
fi;
done;
done;
mount -o noatime,nodiratime,remount,rw,discard,barrier=0,commit=60,noauto_da_alloc /system /system;
touch $ZIPALIGNDB;
