#!/system/bin/sh
echo "noop" > /sys/block/mtdblock6/queue/scheduler; 
echo "noop" > /sys/block/mtdblock7/queue/scheduler; 
echo "noop" > /sys/block/mtdblock8/queue/scheduler; 
echo "noop" > /sys/block/mtdblock10/queue/scheduler;
echo "noop" > /sys/block/mtdblock11/queue/scheduler;


#Optimizing Non-Rotating Storage
# Optimize non-rotating storage; 
#for mtdblock5
	#IMPORTANT!
	if [ -e /sys/block/mtdblock5/queue/rotational ]; 
	then
		echo 0 > /sys/block/mtdblock5/queue/rotational; 
	fi;
	if [ -e /sys/block/mtdblock5/queue/nr_requests ];
	then
		echo 8192 > /sys/block/mtdblock5/queue/nr_requests; # for starters: keep it sane
	fi;
	
	# deadline/VR/SIO scheduler specific
	if [ -e /sys/block/mtdblock5/queue/iosched/fifo_batch ];
	then
		echo 1 > /sys/block/mtdblock5/queue/iosched/fifo_batch;
	fi;
	if [ -e /sys/block/mtdblock5/queue/iosched/writes_starved ];
	then
		echo 1 > /sys/block/mtdblock5/queue/iosched/writes_starved;
	fi;
	
#Disabling I/O Stats To Reduce Overhead
	if [ -e /sys/block/mtdblock5/queue/iostats ];
	then
		echo "0" > /sys/block/mtdblock5/queue/iostats;
	fi;

#for mtdblock6
	#IMPORTANT!
	if [ -e /sys/block/mtdblock6/queue/rotational ]; 
	then
		echo 0 > /sys/block/mtdblock6/queue/rotational; 
	fi;
	if [ -e /sys/block/mtdblock6/queue/nr_requests ];
	then
		echo 8192 > /sys/block/mtdblock6/queue/nr_requests; # for starters: keep it sane
	fi;
	
	# deadline/VR/SIO scheduler specific
	if [ -e /sys/block/mtdblock6/queue/iosched/fifo_batch ];
	then
		echo 1 > /sys/block/mtdblock6/queue/iosched/fifo_batch;
	fi;
	if [ -e /sys/block/mtdblock6/queue/iosched/writes_starved ];
	then
		echo 1 > /sys/block/mtdblock6/queue/iosched/writes_starved;
	fi;
	
#Disabling I/O Stats To Reduce Overhead
	if [ -e /sys/block/mtdblock6/queue/iostats ];
	then
		echo "0" > /sys/block/mtdblock6/queue/iostats;
	fi;

#for mtdblock7
	#IMPORTANT!
	if [ -e /sys/block/mtdblock7/queue/rotational ]; 
	then
		echo 0 > /sys/block/mtdblock7/queue/rotational; 
	fi;
	if [ -e /sys/block/mtdblock7/queue/nr_requests ];
	then
		echo 8192 > /sys/block/mtdblock7/queue/nr_requests; # for starters: keep it sane
	fi;
	
	# deadline/VR/SIO scheduler specific
	if [ -e /sys/block/mtdblock7/queue/iosched/fifo_batch ];
	then
		echo 1 > /sys/block/mtdblock7/queue/iosched/fifo_batch;
	fi;
	if [ -e /sys/block/mtdblock7/queue/iosched/writes_starved ];
	then
		echo 1 > /sys/block/mtdblock7/queue/iosched/writes_starved;
	fi;
	
#Disabling I/O Stats To Reduce Overhead
	if [ -e /sys/block/mtdblock7/queue/iostats ];
	then
		echo "0" > /sys/block/mtdblock7/queue/iostats;
	fi;

#for mtdblock9
	#IMPORTANT!
	if [ -e /sys/block/mtdblock9/queue/rotational ]; 
	then
		echo 0 > /sys/block/mtdblock9/queue/rotational; 
	fi;
	if [ -e /sys/block/mtdblock9/queue/nr_requests ];
	then
		echo 8192 > /sys/block/mtdblock9/queue/nr_requests; # for starters: keep it sane
	fi;
	
	# deadline/VR/SIO scheduler specific
	if [ -e /sys/block/mtdblock9/queue/iosched/fifo_batch ];
	then
		echo 1 > /sys/block/mtdblock9/queue/iosched/fifo_batch;
	fi;
	if [ -e /sys/block/mtdblock9/queue/iosched/writes_starved ];
	then
		echo 1 > /sys/block/mtdblock9/queue/iosched/writes_starved;
	fi;
	
#Disabling I/O Stats To Reduce Overhead
	if [ -e /sys/block/mtdblock9/queue/iostats ];
	then
		echo "0" > /sys/block/mtdblock9/queue/iostats;
	fi;

#for mtdblock10
	#IMPORTANT!
	if [ -e /sys/block/mtdblock10/queue/rotational ]; 
	then
		echo 0 > /sys/block/mtdblock10/queue/rotational; 
	fi;
	if [ -e /sys/block/mtdblock10/queue/nr_requests ];
	then
		echo 8192 > /sys/block/mtdblock10/queue/nr_requests; # for starters: keep it sane
	fi;
	
	# deadline/VR/SIO scheduler specific
	if [ -e /sys/block/mtdblock10/queue/iosched/fifo_batch ];
	then
		echo 1 > /sys/block/mtdblock10/queue/iosched/fifo_batch;
	fi;
	if [ -e /sys/block/mtdblock10/queue/iosched/writes_starved ];
	then
		echo 1 > /sys/block/mtdblock10/queue/iosched/writes_starved;
	fi;
	
#Disabling I/O Stats To Reduce Overhead
	if [ -e /sys/block/mtdblock10/queue/iostats ];
	then
		echo "0" > /sys/block/mtdblock10/queue/iostats;
	fi;

#Boosting R/W
echo "4096" > /sys/devices/virtual/bdi/31:5/read_ahead_kb;
echo "4096" > /sys/devices/virtual/bdi/31:6/read_ahead_kb;
echo "4096" > /sys/devices/virtual/bdi/31:7/read_ahead_kb;
echo "2048" > /sys/devices/virtual/bdi/31:9/read_ahead_kb;
echo "4096" > /sys/devices/virtual/bdi/31:10/read_ahead_kb;

#Applying VM Settings
echo 3 > /proc/sys/vm/page-cluster;
echo 3000 > /proc/sys/vm/dirty_expire_centisecs;
echo 500 > /proc/sys/vm/dirty_writeback_centisecs;
echo "5120" > /proc/sys/vm/min_free_kbytes;
echo "0" > /proc/sys/vm/oom_kill_allocating_task;
echo "0" > /proc/sys/vm/panic_on_oom;
echo "35" > /proc/sys/vm/dirty_background_ratio;
echo "70" > /proc/sys/vm/dirty_ratio;
echo "10" > /proc/sys/vm/vfs_cache_pressure;
echo "1" > /proc/sys/vm/overcommit_memory;
echo "4" > /proc/sys/vm/min_free_order_shift;
echo "0" > /proc/sys/vm/laptop_mode;
echo "0" > /proc/sys/vm/block_dump;
echo "1" > /proc/sys/vm/oom_dump_tasks;

#Applying Network Tweaks
echo "0" > /proc/sys/net/ipv4/tcp_timestamps;
echo "1" > /proc/sys/net/ipv4/tcp_tw_reuse;
echo "1" > /proc/sys/net/ipv4/tcp_sack;
echo "1" > /proc/sys/net/ipv4/tcp_dsack;
echo "1" > /proc/sys/net/ipv4/tcp_tw_recycle;
echo "1" > /proc/sys/net/ipv4/tcp_window_scaling;
echo "5" > /proc/sys/net/ipv4/tcp_keepalive_probes;
echo "30" > /proc/sys/net/ipv4/tcp_keepalive_intvl;
echo "30" > /proc/sys/net/ipv4/tcp_fin_timeout;
echo "1" > /proc/sys/net/ipv4/tcp_moderate_rcvbuf;
echo "1" > /proc/sys/net/ipv4/route/flush;
echo "6144" > /proc/sys/net/ipv4/udp_rmem_min;
echo "6144" > /proc/sys/net/ipv4/udp_wmem_min;
echo "1" > /proc/sys/net/ipv4/tcp_rfc1337;
echo "0" > /proc/sys/net/ipv4/ip_no_pmtu_disc;
echo "0" > /proc/sys/net/ipv4/tcp_ecn;
echo "6144 87380 2097152" > /proc/sys/net/ipv4/tcp_wmem;
echo "6144 87380 2097152" > /proc/sys/net/ipv4/tcp_rmem;
echo "1" > /proc/sys/net/ipv4/tcp_fack;
echo "2" > /proc/sys/net/ipv4/tcp_synack_retries;
echo "2" > /proc/sys/net/ipv4/tcp_syn_retries;
echo "1" > /proc/sys/net/ipv4/tcp_no_metrics_save;
echo "1800" > /proc/sys/net/ipv4/tcp_keepalive_time;
echo "0" > /proc/sys/net/ipv4/ip_forward;
echo "0" > /proc/sys/net/ipv4/conf/default/accept_source_route;
echo "0" > /proc/sys/net/ipv4/conf/all/accept_source_route;
echo "0" > /proc/sys/net/ipv4/conf/all/accept_redirects;
echo "0" > /proc/sys/net/ipv4/conf/default/accept_redirects;
echo "0" > /proc/sys/net/ipv4/conf/all/secure_redirects;
echo "0" > /proc/sys/net/ipv4/conf/default/secure_redirects;
echo "0" > /proc/sys/net/ipv4/ip_dynaddr;
echo "1440000" > /proc/sys/net/ipv4/tcp_max_tw_buckets;
echo "57344 57344 524288" > /proc/sys/net/ipv4/tcp_mem;
echo "1440000" > /proc/sys/net/ipv4/tcp_max_tw_buckets;
echo "2097152" > /proc/sys/net/core/rmem_max;
echo "2097152" > /proc/sys/net/core/wmem_max;
echo "262144" > /proc/sys/net/core/rmem_default;
echo "262144" > /proc/sys/net/core/wmem_default;
echo "20480" > /proc/sys/net/core/optmem_max;
echo "2500" > /proc/sys/net/core/netdev_max_backlog;
echo "50" > /proc/sys/net/unix/max_dgram_qlen;

#Applying Kernel and FS Tweaks
echo "30" > /proc/sys/kernel/panic;
echo "0" > /proc/sys/kernel/panic_on_oops;
echo "5000" > /proc/sys/kernel/threads-max;
echo "10" > /proc/sys/fs/lease-break-time;
echo "65536" > /proc/sys/fs/file-max;

#Cleaning Up Junk Files...
rm /data/local/*.apk
rm /data/local/tmp/*.apk
rm /data/*.log
rm /data/log/*.log
rm /cache/*
rm /cache/recovery/*
rm /data/system/dropbox/*.txt
rm /data/backup/pending/*.tmp
rm /data/tombstones/*
rm /mnt/internal_sd/LOST.DIR/*
rm /mnt/external_sd/LOST.DIR/*